In [32]:
import pandas as pd
import numpy as np

dados_pib = pd.read_csv('Dados/pib-regioes.csv')

dados_pib.head()

,Grande Região,Ano,Produto Interno Bruto a preços correntes (Mil Reais),Valor adicionado bruto a preços correntes total (Mil Reais),Valor adicionado bruto a preços correntes da agropecuária (Mil Reais),Valor adicionado bruto a preços correntes da indústria (Mil Reais),"Valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social (Mil Reais)","Valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social (Mil Reais)"
0,Norte,2006,121371647,1.062867e+08,8.911944e+06,3.102192e+07,4.074553e+07,2.560733e+07
1,Norte,2007,135631867,1.187565e+08,9.332192e+06,3.255884e+07,4.803818e+07,2.882734e+07
2,Norte,2008,156676708,1.365819e+08,1.070049e+07,3.932105e+07,5.341470e+07,3.314567e+07
3,Norte,2009,166210201,1.462379e+08,1.191406e+07,3.678444e+07,6.003047e+07,3.750898e+07
4,Norte,2010,207093645,1.829053e+08,1.546056e+07,5.866544e+07,6.639530e+07,4.238402e+07

In [33]:
# Calculando a quantidade de valores nulos
nan_count = dados_pib.isna().sum().sum()
nan_count

0

In [34]:
dados_indice_aneel = pd.read_csv('Dados/indice-satisfacao-aneel.csv')
dados_indice_aneel.head()

,DatGeracaoConjuntoDados,NumAno,DscClassificacao,DescricaoCategoria,SigAgente,NumCNPJ,NumOrdemIASC,MdaIndicadorQualidade,MdaIndicadorSatisfacao,MdaIndicadorFidelidade,...,QtdEscolaridadeV37,QtdEscolaridadeV38,QtdEscolaridadeV39,QtdRendaV41,QtdRendaV42,QtdRendaV43,QtdRendaV44,QtdRendaV45,QtdRendaV46,QtdRendaV47
0,2024-04-01,2022,Concessionaria,"Sul, Sudeste e Centro-Oeste ate 30 mil unidade...",Mux Energia,97578090000134,1,89.998519,75.688265,32.807499,...,27,5.0,NaN,5.0,111,114,13.0,0.0,1.0,1.0
1,2024-04-01,2022,Concessionaria,"Sul, Sudeste e Centro-Oeste ate 30 mil unidade...",Pacto Energia (Forcel),79850574000109,2,88.320504,71.265505,32.116621,...,21,10.0,NaN,14.0,126,95,9.0,2.0,0.0,0.0
2,2024-04-01,2022,Concessionaria,Nordeste,Sulgipe,13255658000196,3,83.727286,69.779408,32.428941,...,19,5.0,NaN,156.0,114,26,6.0,2.0,0.0,0.0
3,2024-04-01,2022,Concessionaria,"Sul, Sudeste e Centro-Oeste ate 30 mil unidade...",Hidropan,91982348000187,4,81.768352,69.002640,27.986111,...,28,11.0,NaN,11.0,76,124,26.0,3.0,0.0,1.0
4,2024-04-01,2022,Concessionaria,Sul e Sudeste acima de 30 mil e ate 400 mil un...,Cooperalianca,83647990000181,5,82.986298,67.246610,30.109290,...,29,7.0,NaN,11.0,155,125,17.0,1.0,0.0,1.0

In [35]:
nan_count = dados_indice_aneel.isna().sum().sum()
proporcao_nulos = nan_count / dados_indice_aneel.size
proporcao_nulos

0.15383307836138024

In [36]:
dados_pib.rename(columns={"Grande Região": "Regiao", "Produto Interno Bruto a preços correntes (Mil Reais)": "PIB"}, inplace=True)
dados_pib = dados_pib[["Regiao", "Ano", "PIB"]]
regioes_pib = dados_pib.groupby(['Regiao', 'Ano'])['PIB'].mean().reset_index()
regioes_pib

          Regiao   Ano           PIB
0   Centro-Oeste  2006  2.034049e+08
1   Centro-Oeste  2007  2.329269e+08
2   Centro-Oeste  2008  2.781389e+08
3   Centro-Oeste  2009  3.094007e+08
4   Centro-Oeste  2010  3.548158e+08
..           ...   ...           ...
70           Sul  2016  1.067358e+09
71           Sul  2017  1.122038e+09
72           Sul  2018  1.195550e+09
73           Sul  2019  1.272105e+09
74           Sul  2020  1.308147e+09

[75 rows x 3 columns]

In [37]:
dados_indice_aneel.rename(columns={"DescricaoCategoria": "Regiao", "NumAno": "Ano"}, inplace=True)

dados_indice_aneel = dados_indice_aneel[["Ano", "DscClassificacao", "Regiao", "MdaIndicadorQualidade"]]

join = dados_indice_aneel.merge(regioes_pib, how='inner', on=['Regiao', 'Ano'])
join

      Ano DscClassificacao    Regiao  MdaIndicadorQualidade           PIB
0    2020   Concessionaria  Nordeste                  83.56  1.079331e+09
1    2020   Concessionaria  Nordeste                  78.47  1.079331e+09
2    2020   Concessionaria  Nordeste                  77.71  1.079331e+09
3    2020   Concessionaria  Nordeste                  75.43  1.079331e+09
4    2020   Concessionaria  Nordeste                  75.89  1.079331e+09
..    ...              ...       ...                    ...           ...
234  2006   Concessionaria     Norte                  54.41  1.213716e+08
235  2006   Concessionaria     Norte                  54.70  1.213716e+08
236  2006   Concessionaria     Norte                  46.08  1.213716e+08
237  2006   Concessionaria     Norte                  46.72  1.213716e+08
238  2006   Concessionaria     Norte                  49.25  1.213716e+08

[239 rows x 5 columns]

In [42]:
pibs = np.array(join.PIB)
indicesQualidade = np.array(join.MdaIndicadorQualidade)

np.corrcoef(pibs, indicesQualidade)

array([[1.        , 0.46526674],
       [0.46526674, 1.        ]])